const names = [
    "~", "`",
    "!", "1",
    "@", "2",
    "#", "3",
    "$", "4",
    "%", "5",
    "^", "6",
    "&", "7",
    "*", "8",
    "(", "9",
    ")", "0",
    "_", "-",
    "+", "=",
    "delete",
    "tab", 
    "Q", "q",
    "W", "w",
    "E", "e",
    "R", "r",
    "T", "t",
    "Y", "y",
    "U", "u",
    "I", "i",
    "O", "o",
    "P", "p",
    "{", "[", 
    "}", "]", 
    "|", "\\", 
    "caps lock",
    "A", "a",
    "S", "s",
    "D", "d",
    "F", "f",
    "G", "g",
    "H", "h",
    "J", "j",
    "K", "k",
    "L", "l",
    ":", ";",
    '"', "'",
    "return",
    "shift", 
    "Z", "z",
    "X", "x",
    "C", "c",
    "V", "v",
    "B", "b",
    "N", "n",
    "M", "m",
    "<", ",",
    ">", ".",
    "?", "/",
    "shift", 
    " "
]
const allKeys = [
    "tilde", "tick",
    "bang", "1",
    "at", "2",
    "hash", "3",
    "dollar", "4",
    "percent", "5",
    "karat", "6",
    "amper", "7",
    "star", "8",
    "paren-left", "9",
    "paren-right", "0",
    "underscore", "-",
    "plus", "equals",
    "delete",
    'tab', 
    "Q", "q",
    "W", "w",
    "E", "e",
    "R", "r",
    "T", "t",
    "Y", "y",
    "U", "u",
    "I", "i",
    "O", "o",
    "P", "p",
    "bracket-left", "brace-left", 
    "bracket-right", "brace-right", 
    "pipe", "back_slash", 
    "caps-lock",
    "A", "a",
    "S", "s",
    "D", "d",
    "F", "f",
    "G", "g",
    "H", "h",
    "J", "j",
    "K", "k",
    "L", "l",
    "colon", "semicolon",
    'quote', "'",
    "return",
    "shift-left", 
    "Z", "z",
    "X", "x",
    "C", "c",
    "V", "v",
    "B", "b",
    "N", "n",
    "M", "m",
    "karet-left", "comma",
    "karet-right", "period",
    "question", "slash",
    "shift-right", 
    "space"
]
window.addEventListener('message', event => {
    const message = event.data;
    console.dir(message) // TODO: remove me!!!
    for(i in allKeys){
        if(message && message[names[i]]){
            document.getElementById('key-'+allKeys[i]).innerHTML = message[names[i]].label
        }else{
            let el = document.getElementById('key-'+allKeys[i])
            if(el){
                el.innerHTML = ""
            }
        }
    }
})
